name: build test

on:
  push:
    branches:
      - "master"

env:
  CONDA_ORIGIN: http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version:
          - 3.8
          - 3.7
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip install MSCheck
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m unittest discover
